version: "3"

services:
  nginx:
    image: nginx:1.29.0
    volumes:
      - ./cont:/usr/share/nginx/html
    ports:
      - '8085:80'
    networks:
      - internal
  baza:
    image: postgres:17.5
    build: 
      context: ./baza
      dockerfile: dockerfile
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ZAQ!2wsx
      POSTGRES_USER: miecieks
      POSTGRES_DB: biblioteka
    volumes:
      - ./baza_dane:/var/lib/postgresql/data
  golang:
    depends_on:
      - baza
    build: /golang
    ports: 
      - '8080:8080'
    restart: on-failure:7 
  pg4:
    image: dpage/pgadmin4:9.4
    ports: 
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: miecieks@mail.pl
      PGADMIN_DEFAULT_PASSWORD: ZAQ!2wsx
    
networks:
  internal:
    driver: bridge